# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build map

on: workflow_dispatch

# We only want one workflow running at a time.
# This feature is in Beta and might change/break any time
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency
concurrency: build_and_deploy_map

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build map
      run: ./build_map.py
      env:
        STRAVA_EMAIL: ${{ secrets.STRAVA_EMAIL }}
        STRAVA_PASSWORD: ${{ secrets.STRAVA_PASSWORD }}
        STRAVA_API_CLIENT_ID: ${{ secrets.STRAVA_API_CLIENT_ID }}
        STRAVA_API_CLIENT_SECRET: ${{ secrets.STRAVA_API_CLIENT_SECRET }}
        THUNDERFOREST_API_KEY: ${{ secrets.THUNDERFOREST_API_KEY }}
    - name: Archive map.html
      uses: actions/upload-artifact@v3
      with:
          name: map.html
          path: map.html
    - name: Deploy map to FTP server
      run: sshpass -p "${SFTP_PASSWORD}" scp -oHostKeyAlgorithms=+ssh-rsa -oPubkeyAcceptedAlgorithms=+ssh-rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null map.html "${SFTP_USERNAME}@${SFTP_HOST}:./index.html"
      env:
        SFTP_HOST: ${{ secrets.SFTP_HOST }}
        SFTP_USERNAME: ${{ secrets.SFTP_USERNAME }}
        SFTP_PASSWORD: ${{ secrets.SFTP_PASSWORD }}
